version: '3.5'
volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.100.87,nolock,soft,rw"
      device: ":/mnt/data/joplin"
services:
  software:
    image: bytemark/webdav
    restart: always
    networks:
      - internal_routeable
    environment:
      SERVER_NAMES: webdav.leejonchapman.com
      AUTH_TYPE: Digest
    labels:
       - "traefik.enable=true"
       - "traefik.frontend.rule=Host:webdav1.leejonchapman.com"
       - "traefik.frontend.passHostHeader=true"
       - "traefik.frontend.headers.SSLRedirect=true"
 # Allow watchtower to monitor container
 ##   - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - data:/var/lib/dav
      - ./user.passwd:/user.passwd
    deploy:
      replicas: 1
networks:
  internal_routeable:
    name: internal_routeable
    external: true
